#!/bin/bash

set -euo pipefail

if [[ $(basename $(pwd)) == "scripts" ]];
then
  echo "Run this from jutils instead"
  exit 1
fi

ln -s $(pwd)/jls/jls $HOME/.local/bin
ln -s $(pwd)/jfind/jfind $HOME/.local/bin
