#!/usr/bin/env python3

import argparse
from pathlib import Path
import os
import pwd
import grp
import time
from dataclasses import dataclass


@dataclass
class FileInfo:
    name: str
    owner: str
    group: str
    last_modified: str
    nlink: str
    mode: str
    size: str

    @property
    def ignored(self):
        return self.name.startswith(".")

    def to_output(self, complete=False):
        if complete:
            return " ".join(
                [
                    self.mode,
                    self.nlink,
                    self.owner,
                    self.group,
                    self.size,
                    self.last_modified,
                    self.name,
                ]
            )
        return self.name


def mode_to_string(is_dir: bool, mode: int):
    s = "d" if is_dir else "-"
    s += "r" if mode & 0o400 == 0o400 else "-"
    s += "w" if mode & 0o200 == 0o200 else "-"
    s += "x" if mode & 0o100 == 0o100 else "-"
    s += "r" if mode & 0o040 == 0o040 else "-"
    s += "w" if mode & 0o020 == 0o020 else "-"
    s += "x" if mode & 0o010 == 0o010 else "-"
    s += "r" if mode & 0o004 == 0o004 else "-"
    s += "w" if mode & 0o002 == 0o002 else "-"
    s += "x" if mode & 0o001 == 0o001 else "-"
    return s


def get_file_info(path: Path):
    stats = path.stat()
    owner = pwd.getpwuid(stats.st_uid).pw_name
    group = grp.getgrgid(stats.st_gid).gr_name
    last_modified = time.strftime("%b %d %H:%M", time.localtime(stats.st_mtime))
    return FileInfo(
        path.name,
        str(owner),
        str(group),
        last_modified,
        str(stats.st_nlink),
        mode_to_string(path.is_dir(), stats.st_mode),
        str(stats.st_size),
    )


def do_ls(args):
    directory = Path(args.directory)
    files = directory.iterdir()

    files = sorted(files, key=lambda x: x.name)

    ret = []
    for file in files:
        info = get_file_info(file)
        if info.ignored and not args.all:
            continue

        ret.append(info.to_output(args.list))

    return " ".join(ret) if not args.list else "\n".join(ret)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        add_help=True,
        description="List information about the FILEs (the current directory by default)",
    )
    parser.add_argument("directory", default=".", nargs="?")
    parser.add_argument("-a", "--all", action="store_true")
    parser.add_argument("-l", "--list", action="store_true")
    args = parser.parse_args()

    print(do_ls(args))
